import { useCallback, useEffect, useRef, useState } from 'react';
import { io } from 'socket.io-client';
import { Plus, X, Clock, Hospital, MapPin, Check, Pencil, Trash2 } from 'lucide-react';
import api, { API_URL, getActiveMode, getStoredUser, getToken } from '../lib/api';
import DateTimePicker from '../components/DateTimePicker';

export default function EmergencyBoard(){
 const user=getStoredUser(); const mode=getActiveMode(); const [requests,setRequests]=useState([]); const [searchRequests,setSearchRequests]=useState([]); const [show,setShow]=useState(false); const [message,setMessage]=useState(''); const [submitting,setSubmitting]=useState(false); const [editing,setEditing]=useState(null); const [editForm,setEditForm]=useState(null); const submitLock=useRef(false); const [form,setForm]=useState({patientName:'',bloodGroup:'A+',hospitalName:'',hospitalAddress:'',contactNumber:'',bagsRequired:1,neededAt:''});
 const load=useCallback(async()=>{try{const endpoints=mode==='donor'?['/api/requests/incoming/emergency','/api/requests/incoming']:['/api/requests/mine/emergency','/api/requests/mine/direct'];const [emergencyResult,searchResult]=await Promise.all(endpoints.map(endpoint=>api.get(endpoint)));setRequests(emergencyResult.data.requests||[]);setSearchRequests(searchResult.data.requests||[]);}catch{setMessage('Could not load requests.');}},[mode]);useEffect(()=>{load();const refreshTimer=window.setInterval(load,30000);const socket=io(API_URL,{auth:{token:getToken()},transports:['websocket','polling']});socket.on('blood_request_changed',load);return()=>{window.clearInterval(refreshTimer);socket.off('blood_request_changed',load);socket.disconnect();};},[load]);
 const submit=async(e)=>{e.preventDefault();if(submitLock.current)return;submitLock.current=true;setSubmitting(true);try{const neededTime=new Date(form.neededAt);const coords=await getGps();await api.post('/api/requests/create',{...form,neededTime,requestType:'emergency',latitude:coords?.lat,longitude:coords?.lng});setMessage('Emergency request posted and sent to eligible donors.');setShow(false);load();}catch(e){setMessage(e.response?.data?.message||'Request failed.');}finally{submitLock.current=false;setSubmitting(false);}};
 const cancel=async(id)=>{try{await api.patch(`/api/requests/${id}/cancel`);load();}catch(e){setMessage(e.response?.data?.message||'Cancel failed.');}};
 const respond=async(id,status)=>{try{await api.patch(`/api/requests/${id}/respond`,{status});setMessage(status==='accepted'?'Emergency request accepted.':'Emergency request removed from your list.');load();}catch(e){setMessage(e.response?.data?.message||'Action failed.');}};
 const openEdit=(request)=>{setEditing(request);setEditForm({patientName:request.patientName,bloodGroup:request.bloodGroup,hospitalName:request.hospitalName,hospitalAddress:request.hospitalAddress,contactNumber:request.contactNumber,bagsRequired:request.bagsRequired,neededAt:toLocalInputValue(new Date(request.neededTime))});};
 const saveEdit=async(event)=>{event.preventDefault();setSubmitting(true);try{await api.put(`/api/requests/${editing._id}`,{...editForm,neededTime:new Date(editForm.neededAt)});setEditing(null);setEditForm(null);setMessage('Emergency request updated successfully.');load();}catch(e){setMessage(e.response?.data?.message||'Update failed.');}finally{setSubmitting(false);}};
 const remove=async(id)=>{if(!window.confirm('Delete this emergency request permanently?'))return;try{await api.delete(`/api/requests/${id}`);setMessage('Emergency request deleted.');load();}catch(e){setMessage(e.response?.data?.message||'Delete failed.');}};
 return <div className="min-h-screen bg-slate-950 text-white p-6"><div className="max-w-6xl mx-auto pt-10"><div className="flex flex-col md:flex-row justify-between gap-5 mb-8"><div><p className="text-red-400 text-xs font-black uppercase tracking-widest">{mode==='donor'?'Donor Mode':'Recipient Mode'}</p><h1 className="text-4xl font-black">{mode==='donor'?'Donor Request Center':'My Request Center'}</h1></div>{mode==='recipient'&&<button onClick={()=>setShow(true)} className="bg-red-600 rounded-xl px-5 py-3 font-black"><Plus className="inline w-4 h-4 mr-2"/>Post Emergency Need</button>}</div>{message&&<p className="mb-5 text-emerald-400">{message}</p>}
 <RequestBox title={mode==='donor'?'Emergency Requests':'My Emergency Requests'} emergency empty={mode==='donor'?'No matching emergency requests for you.':'You have no active emergency requests.'} requests={requests} user={user} mode={mode} onCancel={cancel} onRespond={respond} onEdit={openEdit} onDelete={remove}/>
 <RequestBox title={mode==='donor'?'Incoming Search Requests':'My Search Requests'} empty={mode==='donor'?'No incoming donor-search requests.':'You have no donor-search requests.'} requests={searchRequests} user={user} mode={mode} onCancel={cancel} onRespond={respond} onEdit={openEdit} onDelete={remove}/>
 {show&&<div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center overflow-y-auto p-4"><form onSubmit={submit} className="w-full max-w-xl bg-slate-900 border border-slate-800 rounded-3xl p-6"><div className="flex justify-between mb-5"><h2 className="text-2xl font-black">New Emergency Request</h2><button type="button" disabled={submitting} onClick={()=>setShow(false)} aria-label="Close emergency request form"><X/></button></div><fieldset disabled={submitting} className="grid md:grid-cols-2 gap-3">{['patientName','hospitalName','hospitalAddress','contactNumber'].map(n=><input key={n} name={n} required value={form[n]} onChange={e=>setForm(p=>({...p,[n]:e.target.value}))} placeholder={n} className={input}/>)}<select name="bloodGroup" value={form.bloodGroup} onChange={e=>setForm(p=>({...p,bloodGroup:e.target.value}))} className={input}>{['A+','A-','B+','B-','AB+','AB-','O+', 'O-'].map(x=><option key={x}>{x}</option>)}</select><input type="number" min="1" name="bagsRequired" value={form.bagsRequired} onChange={e=>setForm(p=>({...p,bagsRequired:e.target.value}))} className={input}/><DateTimePicker value={form.neededAt} onChange={neededAt=>setForm(p=>({...p,neededAt}))}/></fieldset><button disabled={submitting} className="w-full mt-4 bg-red-600 rounded-xl py-3 font-black">{submitting?'Sending Emergency Request...':'Emergency Request'}</button></form></div>}
 {editing&&editForm&&<div className="fixed inset-0 z-[60] flex items-start justify-center bg-black/75 p-4"><form onSubmit={saveEdit} className="max-h-[calc(100vh-2rem)] w-full max-w-xl overflow-y-auto rounded-3xl border border-slate-700 bg-slate-900 p-6"><div className="sticky -top-6 z-10 mb-5 flex justify-between border-b border-slate-800 bg-slate-900 py-4"><h2 className="text-2xl font-black">Edit Emergency Request</h2><button type="button" onClick={()=>setEditing(null)} className="rounded-xl bg-slate-800 p-2"><X/></button></div><fieldset disabled={submitting} className="grid gap-3 md:grid-cols-2">{['patientName','hospitalName','hospitalAddress','contactNumber'].map(n=><input key={n} required value={editForm[n]} onChange={e=>setEditForm(p=>({...p,[n]:e.target.value}))} placeholder={n} className={input}/>)}<select value={editForm.bloodGroup} onChange={e=>setEditForm(p=>({...p,bloodGroup:e.target.value}))} className={input}>{['A+','A-','B+','B-','AB+','AB-','O+','O-'].map(x=><option key={x}>{x}</option>)}</select><input type="number" min="1" max="20" value={editForm.bagsRequired} onChange={e=>setEditForm(p=>({...p,bagsRequired:e.target.value}))} className={input}/><DateTimePicker value={editForm.neededAt} onChange={neededAt=>setEditForm(p=>({...p,neededAt}))}/></fieldset><button disabled={submitting} className="mt-4 w-full rounded-xl bg-red-600 py-3 font-black">{submitting?'Saving...':'Save Changes'}</button></form></div>}
 </div></div>;
}
function Card({r,user,mode,onCancel,onRespond,onEdit,onDelete}){const accepted=(r.responses||[]).filter(x=>x.status==='accepted').length;const ownResponse=(r.responses||[]).find(x=>String(x.donorId?._id||x.donorId)===String(user.id));return <div className="bg-slate-900/70 border border-slate-800 rounded-3xl p-6"><div className="flex justify-between"><div><span className="bg-red-600 px-3 py-1 rounded-lg text-xs font-black">{r.bloodGroup}</span><h3 className="text-xl font-black mt-3">Patient: {r.patientName}</h3></div><div className="text-center"><p className="text-xs text-slate-500">Accepted by</p><p className="text-3xl font-black text-emerald-400">{accepted}</p><p className="text-xs text-slate-500">donor(s)</p></div></div><div className="mt-4 space-y-2 text-sm text-slate-400"><p><Hospital className="inline w-4 h-4 mr-1"/>{r.hospitalName}</p><p><MapPin className="inline w-4 h-4 mr-1"/>{r.hospitalAddress}</p><p><Clock className="inline w-4 h-4 mr-1"/>Needed: {new Date(r.neededTime).toLocaleString()}</p></div>{mode==='recipient'&&String(r.recipientId?._id||r.recipientId)===String(user.id)&&(accepted>0?<div className="mt-4 rounded-xl bg-emerald-500/10 p-3 text-sm font-bold text-emerald-400">Accepted by a donor — Edit and Delete are locked.</div>:<div className="mt-5 grid grid-cols-3 gap-2"><button onClick={()=>onEdit(r)} className="rounded-xl bg-slate-700 py-3 font-bold"><Pencil className="mr-1 inline h-4 w-4"/>Edit</button><button onClick={()=>onDelete(r._id)} className="rounded-xl bg-red-600/20 py-3 font-bold text-red-300"><Trash2 className="mr-1 inline h-4 w-4"/>Delete</button><button onClick={()=>onCancel(r._id)} className="rounded-xl bg-slate-800 py-3 font-bold text-slate-300">Cancel</button></div>)}{mode==='donor'&&(ownResponse?.status==='accepted'?<div className="mt-4 rounded-xl bg-emerald-500/10 p-3 font-bold text-emerald-400">Accepted</div>:<div className="mt-5 flex gap-3"><button onClick={()=>onRespond(r._id,'accepted')} className="flex-1 rounded-xl bg-emerald-600 py-3 font-bold"><Check className="mr-1 inline h-4 w-4"/>Accept</button><button onClick={()=>onRespond(r._id,'rejected')} className="flex-1 rounded-xl bg-slate-800 py-3 font-bold"><X className="mr-1 inline h-4 w-4"/>Reject</button></div>)}</div>}
function RequestBox({title,empty,requests,emergency,user,mode,onCancel,onRespond,onEdit,onDelete}){return <section className={`mb-10 rounded-3xl border p-5 md:p-7 ${emergency?'border-red-500/30 bg-red-500/5':'border-slate-800 bg-slate-900/30'}`}><div className="mb-5 flex items-center gap-3"><h2 className="text-2xl font-black">{title}</h2>{emergency&&<span className="rounded-full bg-red-600 px-3 py-1 text-xs font-black">EMERGENCY</span>}</div>{requests.length===0?<div className="rounded-2xl border border-dashed border-slate-700 p-10 text-center text-slate-500">{empty}</div>:<div className="grid gap-5 md:grid-cols-2">{requests.map(r=><Card key={r._id} r={r} user={user} mode={mode} onCancel={onCancel} onRespond={onRespond} onEdit={onEdit} onDelete={onDelete}/>)}</div>}</section>}
const input='w-full bg-slate-950 border border-slate-800 rounded-xl px-4 py-3';
async function getGps(){return new Promise((resolve)=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition((p)=>resolve({lat:p.coords.latitude,lng:p.coords.longitude}),()=>resolve(null),{timeout:3000});});}
function toLocalInputValue(date){const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16);}
