import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Mail, Lock, LogIn } from 'lucide-react';
import api, { saveSession } from '../lib/api';
import { getAccuratePosition } from '../lib/geolocation';

export default function Login(){
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  const submit=async(e)=>{e.preventDefault();setLoading(true);setError('');try{let coords={};try{coords=await getAccuratePosition();}catch{/* Login continues without refreshing GPS when permission/location is unavailable. */}const {data}=await api.post('/api/auth/login',{email,password,...coords});saveSession(data.token,data.user);window.location.assign('/dashboard');}catch(err){setError(err.response?.data?.message||err.message||'Login failed.');}finally{setLoading(false);}};
  return <div className="min-h-screen bg-slate-950 text-white p-6 flex items-center justify-center"><div className="w-full max-w-md bg-slate-900/70 border border-slate-800 rounded-3xl p-8"><h1 className="text-4xl font-black text-red-500 text-center">Welcome Back</h1><p className="text-slate-400 text-center mt-2 mb-8">Login to manage your Blood Connect account</p>{error&&<div className="mb-5 p-4 rounded-xl bg-red-500/10 border border-red-500/30 text-red-400">{error}</div>}<form onSubmit={submit} autoComplete="on" className="space-y-5"><div><label className="text-xs uppercase text-slate-400">Email</label><div className="relative mt-2"><Mail className="absolute left-4 top-3.5 w-4 h-4 text-slate-500"/><input type="email" name="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)} className="w-full bg-slate-950 border border-slate-800 rounded-xl pl-11 pr-4 py-3"/></div></div><div><label className="text-xs uppercase text-slate-400">Password</label><div className="relative mt-2"><Lock className="absolute left-4 top-3.5 w-4 h-4 text-slate-500"/><input type="password" name="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} className="w-full bg-slate-950 border border-slate-800 rounded-xl pl-11 pr-4 py-3"/></div></div><button disabled={loading} className="w-full bg-red-600 rounded-xl py-3.5 font-black disabled:opacity-50"><LogIn className="inline w-4 h-4 mr-2"/>{loading?'Signing in...':'Sign In'}</button></form><p className="text-center text-slate-500 mt-6">No account? <Link to="/register" className="text-red-400">Create one</Link></p></div></div>;
}
